#!/usr/bin/env python3
"""
Reconstruct a multi-cell 4T4R launch pattern for testMAC / ru_emulator from
the DLMIX/ULMIX test vectors that are present locally.

The vector package on this box carries the 4T4R vectors of the official
20-cell patterns (contiguous blocks of 800 = 40 slot configurations x 20
cells for DL, and 20 x 20 for UL) but not the launch_pattern_*.yaml files
that schedule them. A pattern file is only a schedule: for every slot and
cell it names the vector to replay and which channels to take from it.
The id layout inside a block is

    id(slot_config s, cell c) = base + 20 * s + c

which is the same convention the shipped pattern-69 files use (stride 15
there, since mMIMO patterns are 15-cell). This script writes a
DDDSUUDDDD (mu=1, 40-slot) schedule that walks the DL block's 40 slot
configurations over the DL slots and a chosen subset of the UL block's
configurations over the UL slots.

Defaults reproduce the heaviest 4T4R content found on this box
(see docs): DL block 11432 (6 PDSCH UEs, 273 PRB x 4 layers, MCS 27,
~130 kB/slot, SSB + CSI-RS + PDCCH), UL block 5971 (6 PUSCH UEs up to
273 PRB x 2 layers, 36..108 PUCCH, PRACH).

    make_launch_pattern_4t4r.py --cells 4 --name 59c --out testVectors/

writes testVectors/launch_pattern_F08_4C_59c.yaml. The name is what
test_config.sh / run3_testMAC.sh / run1_RU.sh pass to test_mac and
ru_emulator as the pattern id; 59c is the official 4T4R peak pattern name,
whose file is missing here, so the phase-4 scripts accept it as is.
"""
import argparse
import os
import sys

DL_SLOTS = [s for s in range(40) if s % 10 not in (4, 5)]      # DDDSUUDDDD: S carries PDSCH here
UL_SLOTS = [s for s in range(40) if s % 10 in (4, 5)]


def dl_types(cfg_idx, ssb_cfgs, csirs_cfgs):
    t = ["PDSCH", "PDCCH_DL", "PDCCH_UL"]
    if cfg_idx in ssb_cfgs:
        t.append("PBCH")
    if cfg_idx in csirs_cfgs:
        t.append("CSI_RS")
    return t


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--cells", type=int, default=1)
    ap.add_argument("--name", default="59c", help="pattern id used in the file name")
    ap.add_argument("--out", default=".", help="output directory")
    ap.add_argument("--dl-base", type=int, default=11432, help="first id of the DL block (cell 0, slot config 0)")
    ap.add_argument("--ul-base", type=int, default=5971)
    ap.add_argument("--stride", type=int, default=20, help="cells per slot configuration in the block")
    ap.add_argument("--dl-cfgs", default="", help="comma list of DL slot configs to use (default: 0..39 in order)")
    ap.add_argument("--ul-cfgs", default="4,5,6,7,8,9,10,11", help="UL slot configs for the 8 UL slots")
    ap.add_argument("--ssb-cfgs", default="0,1,2,3,4,5,6,7", help="DL configs that carry SSB (checked from the vectors)")
    ap.add_argument("--csirs-cfgs", default="8-21,24-37", help="DL configs that carry CSI-RS")
    ap.add_argument("--prach-cfgs", default="6,7,10,11,14,15,18,19", help="UL configs that carry PRACH")
    ap.add_argument("--tv-dir", default="", help="if set, verify every referenced vector exists there")
    a = ap.parse_args()

    def parse_set(s):
        out = set()
        for tok in s.split(","):
            tok = tok.strip()
            if not tok:
                continue
            if "-" in tok:
                lo, hi = tok.split("-")
                out.update(range(int(lo), int(hi) + 1))
            else:
                out.add(int(tok))
        return out

    if a.cells < 1 or a.cells > a.stride:
        sys.exit("cells must be 1..%d" % a.stride)
    dl_cfgs = [int(x) for x in a.dl_cfgs.split(",")] if a.dl_cfgs else list(range(40))
    ul_cfgs = [int(x) for x in a.ul_cfgs.split(",")]
    ssb, csirs, prach = parse_set(a.ssb_cfgs), parse_set(a.csirs_cfgs), parse_set(a.prach_cfgs)
    if len(ul_cfgs) < len(UL_SLOTS):
        sys.exit("need %d UL configs" % len(UL_SLOTS))

    dl_tv = lambda cfg, c: "TVnr_DLMIX_%d_gNB_FAPI_s0.h5" % (a.dl_base + a.stride * cfg + c)
    ul_tv = lambda cfg, c: "TVnr_ULMIX_%d_gNB_FAPI_s0.h5" % (a.ul_base + a.stride * cfg + c)

    lines = []
    lines.append("# Reconstructed 4T4R %d-cell pattern (DDDSUUDDDD, 40 slots) from local DLMIX/ULMIX blocks" % a.cells)
    lines.append("# DL block %d, UL block %d, stride %d. Generated by cuPHY-CP/dapp_hook/tools/make_launch_pattern_4t4r.py" % (a.dl_base, a.ul_base, a.stride))
    lines.append("Cell_Configs: [%s]" % ", ".join(dl_tv(0, c) for c in range(a.cells)))
    lines.append("UL_Cell_Configs: [%s]" % ", ".join(ul_tv(ul_cfgs[0], c) for c in range(a.cells)))
    lines.append("config_static_harq_proc_id: 1.0")
    lines.append("SCHED:")
    referenced = set()
    dl_i = 0
    ul_i = 0
    for s in range(40):
        lines.append("- config:")
        if s in UL_SLOTS:
            cfg = ul_cfgs[ul_i % len(ul_cfgs)]
            ul_i += 1
            types = ["PUSCH", "PUCCH"] + (["PRACH"] if cfg in prach else [])
            for c in range(a.cells):
                tv = ul_tv(cfg, c)
                referenced.add(tv)
                lines.append("  - cell_index: %d.0" % c)
                lines.append("    channels: [%s]" % tv)
                lines.append("    type: [%s]" % ", ".join(types))
        else:
            cfg = dl_cfgs[dl_i % len(dl_cfgs)]
            dl_i += 1
            types = dl_types(cfg, ssb, csirs)
            for c in range(a.cells):
                tv = dl_tv(cfg, c)
                referenced.add(tv)
                lines.append("  - cell_index: %d.0" % c)
                lines.append("    channels: [%s]" % tv)
                lines.append("    type: [%s]" % ", ".join(types))
        lines.append("  slot: %d.0" % s)

    if a.tv_dir:
        missing = [t for t in sorted(referenced) if not os.path.exists(os.path.join(a.tv_dir, t))]
        if missing:
            sys.exit("missing vectors (%d): %s ..." % (len(missing), ", ".join(missing[:5])))

    fn = os.path.join(a.out, "launch_pattern_F08_%dC_%s.yaml" % (a.cells, a.name))
    with open(fn, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote %s: %d slots, %d cells, %d distinct vectors" % (fn, 40, a.cells, len(referenced)))


if __name__ == "__main__":
    main()
